/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etf.backgammon.dp120263d.grafickiKorisnickiInterface;

import etf.backgammon.dp120263d.Board;
import etf.backgammon.dp120263d.Covek;
import etf.backgammon.dp120263d.Igra;
import etf.backgammon.dp120263d.Igrac;
import etf.backgammon.dp120263d.Racunar;

/**
 *
 * @author Drakulic
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    
    Igrac white,black;
    int tezina,dokleSeIgra;
    public int igra=0;
    Tabla t;
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pocni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BeliIgrac = new javax.swing.JComboBox<>();
        CrniIgrac = new javax.swing.JComboBox<>();
        IgraSeDo = new javax.swing.JComboBox<>();
        Tezina = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("backgammon");
        setResizable(false);

        Pocni.setText("Pocni");
        Pocni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PocniActionPerformed(evt);
            }
        });

        jLabel1.setText("BELI IGRAC:");

        jLabel2.setText("CRNI IGRAC");

        jLabel3.setText("IGRA SE DO");

        jLabel4.setText("TEZINA");

        BeliIgrac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "covek", "racunar" }));

        CrniIgrac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "covek", "racunar" }));

        IgraSeDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "5", "7", "12", "15" }));

        Tezina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel5.setText("BACKGAMMON");

        jLabel6.setText("autor PETAR DRAKULIC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Pocni, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IgraSeDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Tezina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BeliIgrac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(CrniIgrac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BeliIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CrniIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addComponent(IgraSeDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Tezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Pocni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void PocniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PocniActionPerformed
        
        this.setVisible(false);
        
        t = new Tabla();
        Board board=new Board(t);
        t.setVisible(true);
        initGame();
        igra=1;
        
       // t.setVisible(false);
        //this.setVisible(true);
    
     // TODO add your handling code here
        
      // Board.mainTable.tabla.setVisible(true);
      
    }//GEN-LAST:event_PocniActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public Igrac Beli(){
        return white;
    }
    public Igrac Crni(){
        return black;
    }
    public int dokle(){
        return dokleSeIgra;
    }
    
    
   public void initGame(){
       tezina=Tezina();
       dokleSeIgra=IgraSeDo();
       
       
       
       if(BeliIgrac()=="covek")
           white=new Covek("white",Board.mainTable);
       else
           white=new Racunar("white",Board.mainTable,tezina);
       
       if(CrniIgrac()=="covek")
           black=new Covek("black",Board.mainTable);
       else
           black=new Racunar("black",Board.mainTable,tezina);
       
   }
  public String BeliIgrac(){
      return BeliIgrac.getSelectedItem().toString();
  }
   public String CrniIgrac(){
      return CrniIgrac.getSelectedItem().toString();
  }
   public int IgraSeDo(){
       return Integer.parseInt(IgraSeDo.getSelectedItem().toString());
   }
   public int Tezina(){
       return Integer.parseInt(Tezina.getSelectedItem().toString());
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BeliIgrac;
    private javax.swing.JComboBox<String> CrniIgrac;
    private javax.swing.JComboBox<String> IgraSeDo;
    private javax.swing.JButton Pocni;
    private javax.swing.JComboBox<String> Tezina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public boolean pritisnutoDugme() {
        if(igra==0) return false;
        else return true;
    }

    public void ugasiTablu() {
       t.setVisible(false);
    }
}
